// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/module_include_list/module_include_list.go - DO NOT EDIT.

package include

import (
	// Import packages that need to register themselves.
	_ "github.com/elastic/beats/v7/metricbeat/module/beat"
	_ "github.com/elastic/beats/v7/metricbeat/module/beat/state"
	_ "github.com/elastic/beats/v7/metricbeat/module/beat/stats"
	_ "github.com/elastic/beats/v7/metricbeat/module/elasticsearch"
	_ "github.com/elastic/beats/v7/metricbeat/module/elasticsearch/ccr"
	_ "github.com/elastic/beats/v7/metricbeat/module/elasticsearch/cluster_stats"
	_ "github.com/elastic/beats/v7/metricbeat/module/elasticsearch/enrich"
	_ "github.com/elastic/beats/v7/metricbeat/module/elasticsearch/index"
	_ "github.com/elastic/beats/v7/metricbeat/module/elasticsearch/index_recovery"
	_ "github.com/elastic/beats/v7/metricbeat/module/elasticsearch/index_summary"
	_ "github.com/elastic/beats/v7/metricbeat/module/elasticsearch/ml_job"
	_ "github.com/elastic/beats/v7/metricbeat/module/elasticsearch/node"
	_ "github.com/elastic/beats/v7/metricbeat/module/elasticsearch/node_stats"
	_ "github.com/elastic/beats/v7/metricbeat/module/elasticsearch/pending_tasks"
	_ "github.com/elastic/beats/v7/metricbeat/module/elasticsearch/shard"
	_ "github.com/elastic/beats/v7/metricbeat/module/envoyproxy"
	_ "github.com/elastic/beats/v7/metricbeat/module/envoyproxy/server"
	_ "github.com/elastic/beats/v7/metricbeat/module/kibana"
	_ "github.com/elastic/beats/v7/metricbeat/module/kibana/stats"
	_ "github.com/elastic/beats/v7/metricbeat/module/kibana/status"
	_ "github.com/elastic/beats/v7/metricbeat/module/linux"
	_ "github.com/elastic/beats/v7/metricbeat/module/linux/conntrack"
	_ "github.com/elastic/beats/v7/metricbeat/module/linux/ksm"
	_ "github.com/elastic/beats/v7/metricbeat/module/linux/pageinfo"
	_ "github.com/elastic/beats/v7/metricbeat/module/mysql"
	_ "github.com/elastic/beats/v7/metricbeat/module/mysql/galera_status"
	_ "github.com/elastic/beats/v7/metricbeat/module/mysql/status"
	_ "github.com/elastic/beats/v7/metricbeat/module/nginx"
	_ "github.com/elastic/beats/v7/metricbeat/module/nginx/stubstatus"
	_ "github.com/elastic/beats/v7/metricbeat/module/php_fpm"
	_ "github.com/elastic/beats/v7/metricbeat/module/php_fpm/pool"
	_ "github.com/elastic/beats/v7/metricbeat/module/php_fpm/process"
	_ "github.com/elastic/beats/v7/metricbeat/module/postgresql"
	_ "github.com/elastic/beats/v7/metricbeat/module/postgresql/activity"
	_ "github.com/elastic/beats/v7/metricbeat/module/postgresql/bgwriter"
	_ "github.com/elastic/beats/v7/metricbeat/module/postgresql/database"
	_ "github.com/elastic/beats/v7/metricbeat/module/postgresql/statement"
	_ "github.com/elastic/beats/v7/metricbeat/module/prometheus"
	_ "github.com/elastic/beats/v7/metricbeat/module/prometheus/collector"
	_ "github.com/elastic/beats/v7/metricbeat/module/prometheus/query"
	_ "github.com/elastic/beats/v7/metricbeat/module/prometheus/remote_write"
	_ "github.com/elastic/beats/v7/metricbeat/module/redis"
	_ "github.com/elastic/beats/v7/metricbeat/module/redis/info"
	_ "github.com/elastic/beats/v7/metricbeat/module/redis/key"
	_ "github.com/elastic/beats/v7/metricbeat/module/redis/keyspace"
	_ "github.com/elastic/beats/v7/metricbeat/module/system"
	_ "github.com/elastic/beats/v7/metricbeat/module/system/core"
	_ "github.com/elastic/beats/v7/metricbeat/module/system/cpu"
	_ "github.com/elastic/beats/v7/metricbeat/module/system/diskio"
	_ "github.com/elastic/beats/v7/metricbeat/module/system/entropy"
	_ "github.com/elastic/beats/v7/metricbeat/module/system/filesystem"
	_ "github.com/elastic/beats/v7/metricbeat/module/system/fsstat"
	_ "github.com/elastic/beats/v7/metricbeat/module/system/load"
	_ "github.com/elastic/beats/v7/metricbeat/module/system/memory"
	_ "github.com/elastic/beats/v7/metricbeat/module/system/network"
	_ "github.com/elastic/beats/v7/metricbeat/module/system/network_summary"
	_ "github.com/elastic/beats/v7/metricbeat/module/system/process"
	_ "github.com/elastic/beats/v7/metricbeat/module/system/process_summary"
	_ "github.com/elastic/beats/v7/metricbeat/module/system/raid"
	_ "github.com/elastic/beats/v7/metricbeat/module/system/service"
	_ "github.com/elastic/beats/v7/metricbeat/module/system/socket"
	_ "github.com/elastic/beats/v7/metricbeat/module/system/socket_summary"
	_ "github.com/elastic/beats/v7/metricbeat/module/system/uptime"
	_ "github.com/elastic/beats/v7/metricbeat/module/system/users"
	_ "github.com/elastic/beats/v7/metricbeat/module/uwsgi"
	_ "github.com/elastic/beats/v7/metricbeat/module/uwsgi/status"
)
