#!/bin/bash

set -euo pipefail

if [ -n "$ELASTICSEARCH_PASSWORD" ]; then
   echo "output.elasticsearch.password = $ELASTICSEARCH_PASSWORD"
fi


# Check if the the user has invoked the image with flags.
# eg. "modbeat -c modbeat.yml"
if [[ -z $1 ]] || [[ ${1:0:1} == '-' ]] ; then
  exec modbeat "$@"
else
  # They may be looking for a Beat subcommand, like "modbeat setup".
  subcommands=$(modbeat help \
                  | awk 'BEGIN {RS=""; FS="\n"} /Available Commands:/' \
                  | awk '/^\s+/ {print $1}')

  # If we _did_ get a subcommand, pass it to modbeat.
  for subcommand in $subcommands; do
      if [[ $1 == $subcommand ]]; then
        exec modbeat "$@"
      fi
  done
fi

# If neither of those worked, then they have specified the binary they want, so
# just do exactly as they say.
exec "$@"
